/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicartagena.poo.gui;

/**
 *
 * @author Carlos
 */
public class GuiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuCiclistas = new javax.swing.JMenu();
        itemAgregarCiclistaUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuBicicleta = new javax.swing.JMenu();
        itemAgregarInformacionBicicleta = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuCompetencia = new javax.swing.JMenu();
        itemInformacionCompetencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".::: GESTION DE BICICLETAS:::.");

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusColor"));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        MenuCiclistas.setText("Ciclistas");
        MenuCiclistas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        itemAgregarCiclistaUsuario.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemAgregarCiclistaUsuario.setText("Agregar Ciclista");
        itemAgregarCiclistaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarCiclistaUsuarioActionPerformed(evt);
            }
        });
        MenuCiclistas.add(itemAgregarCiclistaUsuario);
        MenuCiclistas.add(jSeparator1);

        BarraMenu.add(MenuCiclistas);

        MenuBicicleta.setText("Bicicleta");
        MenuBicicleta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        itemAgregarInformacionBicicleta.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemAgregarInformacionBicicleta.setText("Agregar Bicicleta...");
        itemAgregarInformacionBicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarInformacionBicicletaActionPerformed(evt);
            }
        });
        MenuBicicleta.add(itemAgregarInformacionBicicleta);
        MenuBicicleta.add(jSeparator2);

        BarraMenu.add(MenuBicicleta);

        MenuCompetencia.setText("Competencia");
        MenuCompetencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        itemInformacionCompetencia.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemInformacionCompetencia.setText("Informacion De La Competencia...");
        itemInformacionCompetencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacionCompetenciaActionPerformed(evt);
            }
        });
        MenuCompetencia.add(itemInformacionCompetencia);

        BarraMenu.add(MenuCompetencia);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemInformacionCompetenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacionCompetenciaActionPerformed
        GuiCompetencia gui = new GuiCompetencia(this,true);
       gui.setLocationRelativeTo(this);
       gui.setVisible(true);
    }//GEN-LAST:event_itemInformacionCompetenciaActionPerformed

    private void itemAgregarInformacionBicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarInformacionBicicletaActionPerformed
      GuiBicicleta gui = new GuiBicicleta(this,true);
       gui.setLocationRelativeTo(this);
       gui.setVisible(true);
    }//GEN-LAST:event_itemAgregarInformacionBicicletaActionPerformed

    private void itemAgregarCiclistaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarCiclistaUsuarioActionPerformed
       GuiUsuarios gui = new GuiUsuarios(this,true);
       gui.setLocationRelativeTo(this);
       gui.setVisible(true);
       
    }//GEN-LAST:event_itemAgregarCiclistaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu MenuBicicleta;
    private javax.swing.JMenu MenuCiclistas;
    private javax.swing.JMenu MenuCompetencia;
    private javax.swing.JMenuItem itemAgregarCiclistaUsuario;
    private javax.swing.JMenuItem itemAgregarInformacionBicicleta;
    private javax.swing.JMenuItem itemInformacionCompetencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
